package com.studio.core.global.enums.order.payment;

public enum TossError {
    PAY_PROCESS_CANCELED,
    NOT_FOUND_PAYMENT_SESSION,
    NOT_CANCELABLE_PAYMENT,
    PAY_PROCESS_ABORTED,
    FORBIDDEN_REQUEST,
    NOT_SUPPORTED_CARD_TYPE,
    REJECT_CARD_COMPANY,
    NOT_CANCELABLE_AMOUNT,
    FAILED_PAYMENT_INTERNAL_SYSTEM_PROCESSING,
    NOT_SUPPORTED_METHOD,
    ALREADY_PROCESSED_PAYMENT
}
